[package]
name = "azula_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azula_error = { path = "../errors" }
azula_ast = { path = "../ast" }
azula_type = { path = "../azula_type" }