name: Azula tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    container:
      image: ubuntu:18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install CURL
      run: apt-get update && apt-get install -y gnupg2 curl
    - name: Add Crystal key
      run: curl -sL "https://keybase.io/crystal/pgp_keys.asc" | apt-key add -
    - name: Add source
      run: echo "deb https://dist.crystal-lang.org/apt crystal main" | tee /etc/apt/sources.list.d/crystal.list
    - name: Update APT
      run: apt-get update
    - name: Install LLVM and Clang
      run: apt-get install -y crystal clang-8
    - name: Create links
      run: ln -s /usr/bin/clang-8 /usr/local/bin/clang && ln -s /usr/bin/llvm-config-8 /usr/local/bin/llvm-config
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
